name = "qol"
author = "joyalzzy"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ab8fb9470fcb855168aeee415f7d164b088eb3d7fb3d0ccffb404f0dee9b816"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
