name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "912cd222e7d4c537432e49825b1fb57a15cea79a41b3001970b03cac4ecde879"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
