name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2942a2e78347ab2edeeb13448b5849a4641af58d6424b32fcc16e85dc425329d"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
