name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bf0f5470a349fe30091e5e856ccceff83599ba94f3417be8644c1e783027e6a"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
