name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1fe295a065226b01f9bf6533e65a3c9d46a9f8461853dc9c2387ba3f82b9b43"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
