name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48ace0ff40c9ada138107c5c2c8c16063f75b3f0233a4021aba7d1790f60eaf3"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "datapacks"
