name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "179fe1cef3ed7222ea57edee1780937841dd363fdfa515920222427db6e7f2af"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
