name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfd1f3b590377be71a6c49e12848cb03f75056a96e6d4480da8b206b366fc7e4"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
datapack-folder = "datapacks"
