name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d18fef519fee99153b4a3c40783f4e0c65562bb7d7339ac18015366e471e58e8"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
