name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fb4258f55380a996d86f0dd704cf44d4a9a3261499427111788d53f386f5d56"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
