name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa67ab083bbdd85bbb864bd3ad2a7295a89fe664b3b368496c6beb353ec68ec"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
