name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f4048c7e23c153db6612feb629168b6d99570bceae98cba3eb40d2337d8afde"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
