name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be38adb2f4f576fc5a026d90a5871a6763ae99000f6142bd2e6a2a4195d96c9f"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
