name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54c433372bb588cd1a95d345bb5ae062dc187a9686b8fc58b32b432ddb46d47c"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
