name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c372c23ad70e59f89a853cf5bb82370b8de85f34ff6d4586a03e2754d26f8fb"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
