name = "smp2.0"
author = "jo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "477007adc4e56ce21253480aa7b1aa3109258edc22151d6c8dfee9d11becb7a7"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
